server:
  port: 8084
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8084/eureka/
    register-with-eureka: false #本身不注册
    fetch-registry: false #本身不注册
spring:
  application:
    name: eureka-server
